node: helloworld
log-path: hello.log
log-level: Debug
manage-port: 8100
manager:
  - username: admin
    password: admin123
use-cert:
  cert-path: config/server.crt
  key-path: config/server.key
  insecure-skip-verify: true
enable-server:
  port: 8101
customize:
