cosmos: world
node: hello

log-level: Debug
log-path: /tmp/hello_log

build-path: ""
bin-path: ""
run-path: "/tmp/hello_run"
etc-path: "/tmp/hello_etc"

manage-port: 8100
manager:
  - username: admin
    password: admin123
use-cert:
  cert-path: config/server.crt
  key-path: config/server.key
  insecure-skip-verify: true
enable-server:
  port: 8101
customize:
